package com.example.zenoinc.rucyc.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String user_id;

    @NotNull
    private String fname;

    @NotNull
    private String lname;

    @NotNull
    private String email;

    @NotNull
    private String password;

    @NotNull
    private String token;
    private Integer photo;
    private java.util.Date birthdate;
    private String weight;
    private String height;
    private String gender;
    private String address;
    private Integer province;
    private Integer city;
    private Integer district;
    private boolean filled;

    @NotNull
    private String status;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String user_id, String fname, String lname, String email, String password, String token, Integer photo, java.util.Date birthdate, String weight, String height, String gender, String address, Integer province, Integer city, Integer district, boolean filled, String status) {
        this.id = id;
        this.user_id = user_id;
        this.fname = fname;
        this.lname = lname;
        this.email = email;
        this.password = password;
        this.token = token;
        this.photo = photo;
        this.birthdate = birthdate;
        this.weight = weight;
        this.height = height;
        this.gender = gender;
        this.address = address;
        this.province = province;
        this.city = city;
        this.district = district;
        this.filled = filled;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUser_id() {
        return user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_id(@NotNull String user_id) {
        this.user_id = user_id;
    }

    @NotNull
    public String getFname() {
        return fname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFname(@NotNull String fname) {
        this.fname = fname;
    }

    @NotNull
    public String getLname() {
        return lname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLname(@NotNull String lname) {
        this.lname = lname;
    }

    @NotNull
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(@NotNull String email) {
        this.email = email;
    }

    @NotNull
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(@NotNull String password) {
        this.password = password;
    }

    @NotNull
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(@NotNull String token) {
        this.token = token;
    }

    public Integer getPhoto() {
        return photo;
    }

    public void setPhoto(Integer photo) {
        this.photo = photo;
    }

    public java.util.Date getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(java.util.Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getProvince() {
        return province;
    }

    public void setProvince(Integer province) {
        this.province = province;
    }

    public Integer getCity() {
        return city;
    }

    public void setCity(Integer city) {
        this.city = city;
    }

    public Integer getDistrict() {
        return district;
    }

    public void setDistrict(Integer district) {
        this.district = district;
    }

    public boolean getFilled() {
        return filled;
    }

    public void setFilled(boolean filled) {
        this.filled = filled;
    }

    @NotNull
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(@NotNull String status) {
        this.status = status;
    }

}
